-- Table participants
CREATE TABLE IF NOT EXISTS participants (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    gpro_identifier BIGINT UNIQUE NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

-- Table raw_races
CREATE TABLE IF NOT EXISTS raw_races (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    season BIGINT,
    race BIGINT,
    pool VARCHAR(50),
    PRIMARY KEY (id)
);

-- Table raw_results
CREATE TABLE IF NOT EXISTS raw_results (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    gpro_manager_id BIGINT,
    name VARCHAR(255),
    q1_position VARCHAR(50),
    q1_lap_time VARCHAR(50),
    q2_position VARCHAR(50),
    q2_lap_time VARCHAR(50),
    starting_grid_position VARCHAR(50),
    starting_grid_cumulated_lap_time VARCHAR(50),
    race_position VARCHAR(50),
    race_time VARCHAR(50),
    raw_race_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_raw_results_raw_race
    FOREIGN KEY (raw_race_id) REFERENCES raw_races(id)
);

-- Table registrations
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    season BIGINT,
    participant_gpro_identifier BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_registrations_participant
    FOREIGN KEY (participant_gpro_identifier) REFERENCES participants(gpro_identifier)
);

-- Table des divisions
CREATE TABLE IF NOT EXISTS leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- auto-incrément compatible PG/MySQL
    level INT NOT NULL,
    pool_name VARCHAR(255) NOT NULL,
    number_of_pool INT NOT NULL
);

-- Table des structures par saison
CREATE TABLE IF NOT EXISTS gpro_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season BIGINT NOT NULL,
    league_id BIGINT NOT NULL,
    CONSTRAINT fk_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE
);

-- Index utile pour chercher rapidement toutes les leagues d'une saison
CREATE INDEX IF NOT EXISTS idx_gpro_structure_season ON gpro_structure(season);